# Generated by Django 4.2.1 on 2023-05-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequeteAnonymisees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_customer", models.BigIntegerField()),
                ("child_number", models.IntegerField(blank=True, null=True)),
                (
                    "csp_name_id",
                    models.TextField(blank=True, db_collation="C", null=True),
                ),
                ("purchase_amount", models.TextField(blank=True, null=True)),
                ("purchase_date", models.DateTimeField(blank=True, null=True)),
                ("nb_collect_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "requete_anonymisees",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RequeteCollecte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nb_collect_id", models.BigIntegerField(blank=True, null=True)),
                ("purchase_amount", models.TextField(blank=True, null=True)),
                (
                    "product_category_name_id",
                    models.TextField(blank=True, db_collation="C", null=True),
                ),
            ],
            options={
                "db_table": "requete_collecte",
                "managed": False,
            },
        ),
    ]
