# Generated by Django 4.2.1 on 2023-05-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appcollect", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCategorieProdCsp",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "csp_name_id",
                    models.TextField(blank=True, db_collation="C", null=True),
                ),
                (
                    "product_category_name_id",
                    models.TextField(blank=True, db_collation="C", null=True),
                ),
            ],
            options={
                "db_table": "data_categorie_prod_csp",
                "managed": False,
            },
        ),
    ]
