# Generated by Django 4.2.1 on 2023-05-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appcollect", "0002_datacategorieprodcsp"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDepenseCsp",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "csp_name_id",
                    models.TextField(blank=True, db_collation="C", null=True),
                ),
                (
                    "purchase_amount",
                    models.TextField(blank=True, db_collation="C", null=True),
                ),
            ],
            options={
                "db_table": "depense_categorie_scp",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="DataCategorieProdCsp",
        ),
    ]
