# Generated by Django 4.2.1 on 2023-05-23 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appcollect", "0004_datapaniermoyencsp"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="datadepensecsp",
            table="depense_categorie_csp",
        ),
    ]
