# Generated by Django 4.2.1 on 2023-06-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appcollect", "0005_alter_datadepensecsp_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDepenseTotalCsp",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "csp_name_id",
                    models.TextField(blank=True, db_collation="C", null=True),
                ),
                (
                    "depense_csp",
                    models.TextField(blank=True, db_collation="C", null=True),
                ),
            ],
            options={
                "db_table": "depense_total_par_csp",
                "managed": False,
            },
        ),
        migrations.AlterModelTable(
            name="datadepensecsp",
            table="depense_detail_csp",
        ),
        migrations.AlterModelTable(
            name="datapaniermoyencsp",
            table="depense_moyen_par_csp",
        ),
    ]
