-- This script was generated by the ERD tool in pgAdmin 4.
-- Veuillez signaler tout problème à https://redmine.postgresql.org/projects/pgadmin4/issues/new si vous trouvez des erreurs. Préciser dans le rapport les étapes pour le reproduire.
BEGIN;


CREATE TABLE IF NOT EXISTS public.csp
(
    id_csp bigserial NOT NULL,
    csp_name name,
    PRIMARY KEY (id_csp),
    UNIQUE (csp_name)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    id_customer bigserial NOT NULL,
    first_name name COLLATE pg_catalog."default" NOT NULL,
    last_name name COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default",
    child_number integer,
    id_collect bigint NOT NULL,
    city_name name,
    csp_name name,
    CONSTRAINT "Customers_pkey" PRIMARY KEY (id_customer),
    UNIQUE (id_collect)
);

CREATE TABLE IF NOT EXISTS public.product_categories
(
    id_product_category bigserial NOT NULL,
    product_category_name name,
    CONSTRAINT "ProductCategories_pkey" PRIMARY KEY (id_product_category),
    UNIQUE (product_category_name)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id_product bigserial NOT NULL,
    product_name name COLLATE pg_catalog."default" NOT NULL,
    product_price numeric,
    CONSTRAINT "Products_pkey" PRIMARY KEY (id_product),
    UNIQUE (product_name)
);

CREATE TABLE IF NOT EXISTS public.purchases
(
    id_purchase bigserial NOT NULL,
    purchase_date timestamp with time zone NOT NULL,
    purchase_amount numeric NOT NULL,
    product_category_name name,
    CONSTRAINT "Purchases_pkey" PRIMARY KEY (id_purchase),
    UNIQUE (product_category_name)
);

CREATE TABLE IF NOT EXISTS public.cities
(
    id_city bigserial NOT NULL,
    city_name name,
    PRIMARY KEY (id_city),
    UNIQUE (city_name)
);

ALTER TABLE IF EXISTS public.customers
    ADD FOREIGN KEY (city_name)
    REFERENCES public.cities (city_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customers
    ADD FOREIGN KEY (csp_name)
    REFERENCES public.csp (csp_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (product_name)
    REFERENCES public.product_categories (product_category_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;